import 'package:shoto/core/utils/text_folding.dart';

/// Turns what a vision model saw into words a person would actually type.
///
/// The on-device model emits English nouns like `Cat`, `Ice cream`, `Skyline`
/// — a fixed vocabulary it was trained on. That is not what anybody searches
/// for. They type "Hund", or "chien", or "kitten", and expect the picture of a
/// dog. This maps between the two.
///
/// Three ideas do all the work:
///
/// 1. **A raw label is always searchable as itself.** Everything below is
///    *additional*. If a label is missing from these tables — or the model is
///    updated and starts emitting a name nobody here predicted — searching
///    its English word still finds it. A gap costs one language on one label;
///    it never costs the feature. That also means over-listing is free: a
///    label written here that the model never emits simply never matches
///    anything, so the tables can be generous.
/// 2. **Synonyms carry the other languages.** One label, several everyday
///    words, in every language the app ships in.
/// 3. **Groups carry the general question.** The model never says "animal";
///    it says `Cat`. Somebody searching "Tier" is asking a broader question
///    than any single label answers, so groups bridge the two.
///
/// ## Which languages are in here, and why that is not the shipped list
///
/// **Every shipped language, plus Arabic.** This file spent several releases
/// holding English and Arabic alone — written when the app shipped in Arabic,
/// and never revisited when [`shipped-languages.md`] swapped that for German,
/// Spanish, French, Italian, Dutch and Portuguese. That sweep replaced the cue
/// vocabulary in seven files and missed this one, so a German user typing
/// "Hund" got nothing from a feature the paywall sells.
///
/// Arabic **stays**, and the distinction is worth stating because it is the
/// opposite call to the one that sweep made. The cue lists it emptied are
/// matched against *recognised text*, and the bundled recogniser cannot return
/// Arabic characters at all — so those words were unreachable by construction.
/// These terms are matched against **what the user types into the search box**,
/// which is governed by their keyboard rather than by the model. An Arabic
/// speaker running the app in English can still type "قطة"; the words cost
/// nothing and they work.
///
/// Pure Dart on purpose — no Flutter imports — so all of it is unit-testable
/// without a widget tree, the same split used by [PerceptualHash] and
/// [ScrollStitcher].
class VisualVocabulary {
  /// Below this, a query matches so much that the results are noise. Two
  /// characters is enough for "قط" to find a cat.
  static const int minimumQueryLength = 2;

  /// Labels that describe the *medium*, not the subject.
  ///
  /// This list is the difference between the feature working and the feature
  /// looking broken, and it was found by reading the real database rather
  /// than by reasoning: almost every row in a live library was
  /// `["Screenshot"]`, `["Mobile phone","Screenshot"]`, or
  /// `["Product","Screenshot","Mobile phone","Web page"]`.
  ///
  /// The reason is structural. The model describes the whole frame, and the
  /// whole frame is a phone screen — so a screenshot *of a dog* scores
  /// "Screenshot" around 0.9 and "Dog" far lower, because the dog occupies a
  /// fraction of the picture. Keeping these labels does active harm twice
  /// over: they crowd out the real subject under any confidence threshold,
  /// and they make "shows something" match every screenshot in the library,
  /// which is the same as matching nothing.
  ///
  /// Dropped at both ends — never stored, and filtered again when reading, so
  /// libraries indexed before this existed are cleaned up on the way out.
  static const Set<String> mediumLabels = {
    'Screenshot',
    'Mobile phone',
    'Smartphone',
    'Telephone',
    'Portable communications device',
    'Communication Device',
    'Gadget',
    'Electronic device',
    'Display device',
    'Screen',
    'Technology',
    'Software',
    'Web page',
    'Website',
    'Multimedia',
    'Font',
    'Text',
    'Line',
    'Parallel',
    'Rectangle',
    'Circle',
    'Number',
    'Icon',
    'Logo',
    'Brand',
    'Material property',
    'Colorfulness',
    'Azure',
    'Product',
    'Paper',
    'Document',
  };

  /// Whether [label] says something about what a picture is *of*.
  static bool isMeaningful(String label) => !mediumLabels.contains(label);

  /// [labels] with the medium-describing ones removed.
  static List<String> meaningful(Iterable<String> labels) => [
    for (final String label in labels)
      if (isMeaningful(label)) label,
  ];

  /// Everyday words for a single label, in every language the app ships in.
  ///
  /// Accents and Arabic spelling are both written naturally here — [normalize]
  /// runs over these terms and over the query alike, so "Kase" finds "Käse"
  /// and "قطه" finds "قطة" without any table being spelled defensively.
  static const Map<String, List<String>> synonyms = {
    'Cat': [
      'قطة',
      'قطط',
      'بسة',
      'هرة',
      'kitten',
      'katze',
      'kätzchen',
      'gato',
      'gatito',
      'chat',
      'chaton',
      'gatto',
      'gattino',
      'kat',
      'poes',
      'gata',
    ],
    'Dog': [
      'كلب',
      'كلاب',
      'جرو',
      'puppy',
      'hund',
      'welpe',
      'perro',
      'cachorro',
      'chien',
      'chiot',
      'cane',
      'cucciolo',
      'hond',
      'cão',
      'cao',
    ],
    // Labels the live model actually emitted on this user's library that had
    // no everyday word attached — so the evidence was there and unreachable.
    'Snout': [
      'وجه حيوان',
      'خطم',
      'schnauze',
      'hocico',
      'museau',
      'muso',
      'snuit',
      'focinho',
    ],
    'Whiskers': [
      'شوارب',
      'schnurrhaare',
      'bigotes',
      'moustaches',
      'baffi',
      'snorharen',
    ],
    'Fur': [
      'فرو',
      'فراء',
      'fell',
      'pelaje',
      'fourrure',
      'pelliccia',
      'vacht',
      'pelo',
    ],
    'Bird': [
      'طير',
      'طيور',
      'عصفور',
      'vogel',
      'pájaro',
      'ave',
      'oiseau',
      'uccello',
      'pássaro',
    ],
    'Fish': [
      'سمك',
      'سمكة',
      'أسماك',
      'fisch',
      'pez',
      'pescado',
      'poisson',
      'pesce',
      'vis',
      'peixe',
    ],
    'Horse': [
      'حصان',
      'خيل',
      'أحصنة',
      'pferd',
      'caballo',
      'cheval',
      'cavallo',
      'paard',
    ],
    'Butterfly': [
      'فراشة',
      'فراشات',
      'schmetterling',
      'mariposa',
      'papillon',
      'farfalla',
      'vlinder',
      'borboleta',
    ],
    'Insect': [
      'حشرة',
      'حشرات',
      'insekt',
      'insecto',
      'insecte',
      'insetto',
      'insect',
      'inseto',
    ],
    'Rabbit': [
      'أرنب',
      'أرانب',
      'kaninchen',
      'hase',
      'conejo',
      'lapin',
      'coniglio',
      'konijn',
      'coelho',
    ],
    'Lion': ['أسد', 'سبع', 'löwe', 'león', 'lion', 'leone', 'leeuw', 'leão'],
    'Tiger': ['نمر', 'tigre', 'tijger'],
    'Elephant': ['فيل', 'elefant', 'elefante', 'éléphant', 'olifant'],
    'Monkey': ['قرد', 'affe', 'mono', 'singe', 'scimmia', 'aap', 'macaco'],
    'Bear': ['دب', 'bär', 'oso', 'ours', 'orso', 'beer', 'urso'],
    'Snake': [
      'ثعبان',
      'حية',
      'أفعى',
      'schlange',
      'serpiente',
      'serpent',
      'serpente',
      'slang',
      'cobra',
    ],
    'Turtle': [
      'سلحفاة',
      'schildkröte',
      'tortuga',
      'tortue',
      'tartaruga',
      'schildpad',
    ],
    'Sheep': [
      'خروف',
      'غنم',
      'schaf',
      'oveja',
      'mouton',
      'pecora',
      'schaap',
      'ovelha',
    ],
    'Cattle': [
      'بقرة',
      'بقر',
      'ثور',
      'cow',
      'kuh',
      'rind',
      'vaca',
      'vache',
      'mucca',
      'koe',
    ],
    'Chicken': [
      'دجاجة',
      'دجاج',
      'فروج',
      'huhn',
      'hähnchen',
      'pollo',
      'gallina',
      'poulet',
      'kip',
      'frango',
    ],
    'Duck': ['بطة', 'بط', 'ente', 'pato', 'canard', 'anatra', 'eend'],
    'Camel': [
      'جمل',
      'ناقة',
      'kamel',
      'camello',
      'chameau',
      'cammello',
      'kameel',
      'camelo',
    ],
    'Pet': [
      'حيوان أليف',
      'أليف',
      'pets',
      'haustier',
      'mascota',
      'animal de compagnie',
      'animale domestico',
      'huisdier',
      'animal de estimação',
    ],

    'Food': [
      'أكل',
      'طعام',
      'وجبة',
      'essen',
      'speise',
      'comida',
      'nourriture',
      'repas',
      'cibo',
      'eten',
      'voedsel',
    ],
    'Dessert': [
      'حلى',
      'حلويات',
      'تحلية',
      'nachtisch',
      'postre',
      'dolce',
      'toetje',
      'nagerecht',
      'sobremesa',
    ],
    'Cake': [
      'كيك',
      'كيكة',
      'قالب حلى',
      'تورتة',
      'kuchen',
      'torte',
      'pastel',
      'tarta',
      'gâteau',
      'torta',
      'taart',
      'bolo',
    ],
    'Bread': ['خبز', 'عيش', 'brot', 'pan', 'pain', 'pane', 'brood', 'pão'],
    'Fruit': ['فاكهة', 'فواكه', 'obst', 'frucht', 'fruta', 'frutta', 'frutas'],
    'Vegetable': [
      'خضار',
      'خضروات',
      'gemüse',
      'verdura',
      'légume',
      'groente',
      'legume',
      'verduras',
    ],
    'Ice cream': [
      'بوظة',
      'آيس كريم',
      'جيلاتي',
      'eis',
      'eiscreme',
      'helado',
      'glace',
      'gelato',
      'ijs',
      'gelado',
      'sorvete',
    ],
    'Pizza': ['بيتزا'],
    'Hamburger': ['برجر', 'برغر', 'burger', 'hamburguesa', 'hambúrguer'],
    'Sandwich': [
      'ساندويش',
      'شطيرة',
      'brötchen',
      'bocadillo',
      'sándwich',
      'panino',
      'broodje',
      'sanduíche',
    ],
    'Rice': ['رز', 'أرز', 'reis', 'arroz', 'riz', 'riso', 'rijst'],
    'Meat': ['لحم', 'لحمة', 'fleisch', 'carne', 'viande', 'vlees'],
    'Soup': [
      'شوربة',
      'حساء',
      'suppe',
      'sopa',
      'soupe',
      'zuppa',
      'minestra',
      'soep',
    ],
    'Salad': ['سلطة', 'salat', 'ensalada', 'salade', 'insalata', 'salada'],
    'Coffee': [
      'قهوة',
      'كوفي',
      'اسبريسو',
      'kaffee',
      'café',
      'caffè',
      'koffie',
      'espresso',
    ],
    'Tea': ['شاي', 'tee', 'té', 'thé', 'tè', 'thee', 'chá'],
    'Drink': [
      'مشروب',
      'عصير',
      'juice',
      'getränk',
      'bebida',
      'boisson',
      'bevanda',
      'drankje',
    ],
    'Cooking': [
      'طبخ',
      'وصفة',
      'recipe',
      'kochen',
      'rezept',
      'cocina',
      'receta',
      'cuisine',
      'recette',
      'cucina',
      'ricetta',
      'koken',
      'recept',
      'receita',
    ],
    'Restaurant': ['مطعم', 'restaurante', 'ristorante'],

    'Person': [
      'شخص',
      'انسان',
      'ناس',
      'person',
      'mensch',
      'persona',
      'personne',
      'persoon',
      'pessoa',
    ],
    'Selfie': ['سيلفي', 'صورة شخصية', 'selfie', 'autofoto'],
    'Smile': [
      'ابتسامة',
      'ضحكة',
      'lächeln',
      'sonrisa',
      'sourire',
      'sorriso',
      'glimlach',
    ],
    'Baby': ['طفل', 'بيبي', 'رضيع', 'bebé', 'bébé', 'neonato', 'baby', 'bebê'],
    'Child': [
      'طفل',
      'أطفال',
      'ولد',
      'kind',
      'niño',
      'enfant',
      'bambino',
      'criança',
    ],
    'Crowd': [
      'زحمة',
      'حشد',
      'جمهور',
      'menschenmenge',
      'multitud',
      'foule',
      'folla',
      'menigte',
      'multidão',
    ],
    'Wedding': [
      'عرس',
      'زفاف',
      'فرح',
      'hochzeit',
      'boda',
      'mariage',
      'matrimonio',
      'bruiloft',
      'casamento',
    ],
    'Hairstyle': [
      'تسريحة',
      'شعر',
      'قصة شعر',
      'frisur',
      'peinado',
      'coiffure',
      'acconciatura',
      'kapsel',
      'penteado',
    ],
    'Nail': [
      'أظافر',
      'مناكير',
      'nägel',
      'uñas',
      'ongles',
      'unghie',
      'nagels',
      'unhas',
    ],
    'Tattoo': [
      'وشم',
      'تاتو',
      'tätowierung',
      'tatuaje',
      'tatouage',
      'tatuaggio',
      'tatoeage',
      'tatuagem',
    ],

    'Sky': ['سماء', 'سما', 'himmel', 'cielo', 'ciel', 'lucht', 'céu'],
    'Cloud': [
      'غيم',
      'غيوم',
      'سحاب',
      'wolke',
      'nube',
      'nuage',
      'nuvola',
      'wolk',
      'nuvem',
    ],
    'Sunset': [
      'غروب',
      'sonnenuntergang',
      'atardecer',
      'puesta de sol',
      'coucher de soleil',
      'tramonto',
      'zonsondergang',
      'pôr do sol',
    ],
    'Sunrise': [
      'شروق',
      'sonnenaufgang',
      'amanecer',
      'lever de soleil',
      'alba',
      'zonsopgang',
      'nascer do sol',
    ],
    'Beach': [
      'شاطئ',
      'بحر',
      'رملة',
      'strand',
      'playa',
      'plage',
      'spiaggia',
      'praia',
    ],
    'Mountain': [
      'جبل',
      'جبال',
      'berg',
      'montaña',
      'montagne',
      'montagna',
      'montanha',
    ],
    'Snow': ['ثلج', 'تلج', 'schnee', 'nieve', 'neige', 'neve', 'sneeuw'],
    'Waterfall': [
      'شلال',
      'wasserfall',
      'cascada',
      'cascade',
      'cascata',
      'waterval',
      'cachoeira',
    ],
    'Lake': ['بحيرة', 'lago', 'lac', 'meer'],
    'River': [
      'نهر',
      'fluss',
      'río',
      'rivière',
      'fleuve',
      'fiume',
      'rivier',
      'rio',
    ],
    'Forest': [
      'غابة',
      'غابات',
      'wald',
      'bosque',
      'forêt',
      'foresta',
      'bosco',
      'bos',
      'floresta',
    ],
    'Desert': ['صحراء', 'wüste', 'desierto', 'désert', 'deserto', 'woestijn'],
    'Tree': [
      'شجرة',
      'شجر',
      'baum',
      'árbol',
      'arbre',
      'albero',
      'boom',
      'árvore',
    ],
    'Flower': [
      'وردة',
      'ورد',
      'زهرة',
      'زهور',
      'blume',
      'flor',
      'fleur',
      'fiore',
      'bloem',
      'flores',
    ],
    'Plant': [
      'نبتة',
      'نبات',
      'زرع',
      'pflanze',
      'planta',
      'plante',
      'pianta',
      'plant',
    ],
    'Grass': [
      'عشب',
      'حشيش',
      'gras',
      'hierba',
      'césped',
      'herbe',
      'erba',
      'relva',
      'grama',
    ],
    'Garden': [
      'حديقة',
      'جنينة',
      'garten',
      'jardín',
      'jardin',
      'giardino',
      'tuin',
      'jardim',
    ],
    'Rain': ['مطر', 'شتاء', 'regen', 'lluvia', 'pluie', 'pioggia', 'chuva'],
    'Rainbow': [
      'قوس قزح',
      'regenbogen',
      'arcoíris',
      'arc-en-ciel',
      'arcobaleno',
      'regenboog',
      'arco-íris',
    ],
    'Moon': ['قمر', 'mond', 'luna', 'lune', 'maan', 'lua'],
    'Night': ['ليل', 'مسا', 'nacht', 'noche', 'nuit', 'notte', 'noite'],
    'Landscape': [
      'منظر',
      'مناظر',
      'طبيعة خلابة',
      'landschaft',
      'paisaje',
      'paysage',
      'paesaggio',
      'landschap',
      'paisagem',
    ],

    'Car': [
      'سيارة',
      'سيارات',
      'عربية',
      'auto',
      'wagen',
      'coche',
      'carro',
      'voiture',
      'macchina',
    ],
    'Bicycle': [
      'بسكليت',
      'دراجة',
      'bike',
      'fahrrad',
      'bicicleta',
      'bici',
      'vélo',
      'bicicletta',
      'fiets',
    ],
    'Motorcycle': [
      'موتور',
      'دراجة نارية',
      'motorrad',
      'moto',
      'motocicleta',
      'motor',
      'mota',
    ],
    'Boat': ['قارب', 'مركب', 'boot', 'barco', 'bote', 'bateau', 'barca'],
    'Airplane': [
      'طيارة',
      'طائرة',
      'plane',
      'flugzeug',
      'avión',
      'avion',
      'aereo',
      'vliegtuig',
      'avião',
    ],
    'Train': ['قطار', 'zug', 'tren', 'treno', 'trein', 'comboio', 'trem'],
    'Bus': ['باص', 'حافلة', 'autobús', 'autobus', 'autocarro', 'ônibus'],
    'Truck': [
      'شاحنة',
      'تريلا',
      'lastwagen',
      'lkw',
      'camión',
      'camion',
      'vrachtwagen',
      'camião',
      'caminhão',
    ],
    'Road': [
      'شارع',
      'طريق',
      'straße',
      'strasse',
      'carretera',
      'calle',
      'route',
      'rue',
      'strada',
      'weg',
      'estrada',
    ],

    'Building': [
      'مبنى',
      'بناية',
      'عمارة',
      'gebäude',
      'edificio',
      'bâtiment',
      'immeuble',
      'gebouw',
      'prédio',
    ],
    'House': ['بيت', 'منزل', 'دار', 'haus', 'casa', 'maison', 'huis'],
    'Skyscraper': [
      'ناطحة سحاب',
      'برج',
      'wolkenkratzer',
      'rascacielos',
      'gratte-ciel',
      'grattacielo',
      'wolkenkrabber',
      'arranha-céus',
    ],
    'Bridge': ['جسر', 'brücke', 'puente', 'pont', 'ponte', 'brug'],
    'Mosque': [
      'مسجد',
      'جامع',
      'moschee',
      'mezquita',
      'mosquée',
      'moschea',
      'moskee',
      'mesquita',
    ],
    'Church': [
      'كنيسة',
      'kirche',
      'iglesia',
      'église',
      'chiesa',
      'kerk',
      'igreja',
    ],
    'City': ['مدينة', 'stadt', 'ciudad', 'ville', 'città', 'stad', 'cidade'],
    'Room': [
      'غرفة',
      'أوضة',
      'zimmer',
      'raum',
      'habitación',
      'cuarto',
      'pièce',
      'chambre',
      'stanza',
      'camera',
      'kamer',
      'quarto',
    ],
    'Kitchen': [
      'مطبخ',
      'küche',
      'cocina',
      'cuisine',
      'cucina',
      'keuken',
      'cozinha',
    ],
    'Furniture': [
      'أثاث',
      'موبيليا',
      'möbel',
      'muebles',
      'meubles',
      'mobili',
      'meubels',
      'móveis',
    ],
    'Interior design': [
      'ديكور',
      'تصميم داخلي',
      'einrichtung',
      'innenarchitektur',
      'decoración',
      'interiorismo',
      'décoration',
      'arredamento',
      'interieur',
      'decoração',
    ],

    'Sports': ['رياضة', 'sport', 'deporte', 'desporto', 'esporte'],
    'Football': [
      'كرة قدم',
      'فوتبول',
      'soccer',
      'fußball',
      'fussball',
      'fútbol',
      'football',
      'foot',
      'calcio',
      'voetbal',
      'futebol',
    ],
    'Basketball': [
      'كرة سلة',
      'baloncesto',
      'básquet',
      'basket',
      'pallacanestro',
      'basketbal',
      'basquetebol',
    ],
    'Swimming': [
      'سباحة',
      'schwimmen',
      'natación',
      'nadar',
      'natation',
      'nuoto',
      'zwemmen',
      'natação',
    ],
    'Gym': [
      'جيم',
      'نادي',
      'تمرين',
      'fitnessstudio',
      'gimnasio',
      'salle de sport',
      'palestra',
      'sportschool',
      'ginásio',
      'academia',
    ],
    'Running': [
      'ركض',
      'جري',
      'laufen',
      'joggen',
      'correr',
      'course',
      'courir',
      'corsa',
      'hardlopen',
      'corrida',
    ],

    'Music': [
      'موسيقى',
      'أغنية',
      'أغاني',
      'musik',
      'música',
      'musique',
      'musica',
      'muziek',
    ],
    'Guitar': [
      'جيتار',
      'gitarre',
      'guitarra',
      'guitare',
      'chitarra',
      'gitaar',
      'violão',
    ],
    'Piano': ['بيانو', 'klavier', 'pianoforte'],
    'Concert': [
      'حفلة',
      'كونسرت',
      'konzert',
      'concierto',
      'concert',
      'concerto',
      'show',
    ],
    'Dance': [
      'رقص',
      'رقصة',
      'tanz',
      'tanzen',
      'baile',
      'bailar',
      'danse',
      'ballo',
      'danza',
      'dans',
      'dança',
    ],

    'Laptop': [
      'لابتوب',
      'حاسوب محمول',
      'portátil',
      'ordinateur portable',
      'portatile',
      'notebook',
    ],
    'Computer': [
      'كمبيوتر',
      'حاسوب',
      'pc',
      'rechner',
      'ordenador',
      'computadora',
      'ordinateur',
      'computer',
      'computador',
    ],
    'Mobile phone': [
      'موبايل',
      'جوال',
      'تلفون',
      'phone',
      'handy',
      'móvil',
      'celular',
      'téléphone',
      'cellulare',
      'telefoon',
      'mobiel',
      'telemóvel',
    ],
    'Keyboard': [
      'كيبورد',
      'لوحة مفاتيح',
      'tastatur',
      'teclado',
      'clavier',
      'tastiera',
      'toetsenbord',
    ],
    'Camera': [
      'كاميرا',
      'kamera',
      'cámara',
      'appareil photo',
      'caméra',
      'fotocamera',
      'câmara',
      'câmera',
    ],
    'Watch': [
      'ساعة',
      'uhr',
      'reloj',
      'montre',
      'orologio',
      'horloge',
      'relógio',
    ],
    'Television': [
      'تلفزيون',
      'شاشة',
      'tv',
      'fernseher',
      'televisión',
      'tele',
      'télévision',
      'télé',
      'televisione',
      'televisie',
      'televisão',
    ],

    'Book': ['كتاب', 'كتب', 'buch', 'libro', 'livre', 'boek', 'livro'],
    'Newspaper': [
      'جريدة',
      'صحيفة',
      'zeitung',
      'periódico',
      'diario',
      'journal',
      'giornale',
      'krant',
      'jornal',
    ],
    'Handwriting': [
      'خط يد',
      'كتابة يدوية',
      'handschrift',
      'escritura a mano',
      'écriture manuscrite',
      'scrittura a mano',
      'letra manuscrita',
    ],
    'Map': ['خريطة', 'karte', 'mapa', 'carte', 'mappa', 'kaart'],
    'Menu': [
      'منيو',
      'قائمة طعام',
      'speisekarte',
      'menú',
      'carta',
      'menu',
      'menù',
      'menukaart',
      'ementa',
      'cardápio',
    ],
    'Poster': [
      'بوستر',
      'ملصق',
      'plakat',
      'cartel',
      'póster',
      'affiche',
      'manifesto',
      'cartaz',
    ],
    'Calendar': [
      'تقويم',
      'روزنامة',
      'kalender',
      'calendario',
      'calendrier',
      'calendário',
    ],

    'Painting': [
      'لوحة',
      'رسمة',
      'رسم زيتي',
      'gemälde',
      'cuadro',
      'pintura',
      'peinture',
      'tableau',
      'dipinto',
      'quadro',
      'schilderij',
    ],
    'Drawing': [
      'رسم',
      'رسمة',
      'اسكتش',
      'zeichnung',
      'dibujo',
      'dessin',
      'disegno',
      'tekening',
      'desenho',
    ],
    'Comics': [
      'كوميك',
      'قصة مصورة',
      'comic',
      'cómic',
      'bande dessinée',
      'fumetto',
      'strip',
      'banda desenhada',
      'quadrinhos',
    ],
    'Cartoon': [
      'كرتون',
      'رسوم متحركة',
      'zeichentrick',
      'dibujos animados',
      'dessin animé',
      'cartone animato',
      'tekenfilm',
      'desenho animado',
    ],
    'Anime': ['أنمي', 'انمي', 'anime'],
    'Art': ['فن', 'kunst', 'arte', 'art'],

    'Shopping': [
      'تسوق',
      'شوبينغ',
      'einkaufen',
      'compras',
      'achats',
      'acquisti',
      'winkelen',
    ],
    'Clothing': [
      'ملابس',
      'لبس',
      'kleidung',
      'ropa',
      'vêtements',
      'vestiti',
      'abbigliamento',
      'kleding',
      'roupa',
    ],
    'Dress': ['فستان', 'kleid', 'vestido', 'robe', 'abito', 'jurk'],
    'Shoe': [
      'حذاء',
      'جزمة',
      'كندرة',
      'schuh',
      'schuhe',
      'zapato',
      'zapatos',
      'chaussure',
      'scarpa',
      'scarpe',
      'schoen',
      'sapato',
    ],
    'Bag': [
      'شنطة',
      'حقيبة',
      'tasche',
      'bolso',
      'bolsa',
      'sac',
      'borsa',
      'tas',
      'mala',
    ],
    'Jewellery': [
      'مجوهرات',
      'ذهب',
      'jewelry',
      'schmuck',
      'joyas',
      'bijoux',
      'gioielli',
      'sieraden',
      'joias',
    ],
    'Sunglasses': [
      'نظارة شمس',
      'نظارات',
      'sonnenbrille',
      'gafas de sol',
      'lunettes de soleil',
      'occhiali da sole',
      'zonnebril',
      'óculos de sol',
    ],

    'Party': [
      'حفلة',
      'سهرة',
      'party',
      'feier',
      'fiesta',
      'fête',
      'soirée',
      'festa',
      'feest',
    ],
    'Birthday': [
      'عيد ميلاد',
      'ميلاد',
      'geburtstag',
      'cumpleaños',
      'anniversaire',
      'compleanno',
      'verjaardag',
      'aniversário',
    ],
    'Gift': [
      'هدية',
      'هدايا',
      'geschenk',
      'regalo',
      'cadeau',
      'presente',
      'prenda',
    ],
    'Balloon': [
      'بالون',
      'بالونات',
      'luftballon',
      'globo',
      'ballon',
      'palloncino',
      'balão',
    ],
    'Fireworks': [
      'ألعاب نارية',
      'feuerwerk',
      'fuegos artificiales',
      "feu d'artifice",
      "fuochi d'artificio",
      'vuurwerk',
      'fogo de artifício',
    ],

    'Game': ['لعبة', 'ألعاب', 'spiel', 'juego', 'jeu', 'gioco', 'spel', 'jogo'],
    'Video game': [
      'لعبة فيديو',
      'قيمنق',
      'gaming',
      'videospiel',
      'videojuego',
      'jeu vidéo',
      'videogioco',
      'videogame',
      'videojogo',
    ],
    'Toy': [
      'لعبة أطفال',
      'دمية',
      'spielzeug',
      'juguete',
      'jouet',
      'giocattolo',
      'speelgoed',
      'brinquedo',
    ],
  };

  /// Broad everyday categories, each pointing at the specific labels a model
  /// would actually emit for them.
  ///
  /// This is the part that answers "حيوان" with a picture of a cat. Listing a
  /// label the model never produces is harmless, so these lean generous.
  static const List<VisualGroup> groups = [
    VisualGroup(
      terms: [
        'animal',
        'حيوان',
        'حيوانات',
        'حياة برية',
        'wildlife',
        'tier',
        'tiere',
        'animales',
        'animaux',
        'animali',
        'dier',
        'dieren',
        'animais',
      ],
      labels: [
        'Cat',
        'Dog',
        // The model reaches for these when it can see an animal but is not
        // sure which one — which on a cropped screenshot is often. Leaving
        // them out meant the most common evidence of an animal did not count
        // as evidence of an animal.
        'Pet',
        'Snout',
        'Whiskers',
        'Fur',
        'Puppy',
        'Kitten',
        'Bird',
        'Fish',
        'Horse',
        'Butterfly',
        'Insect',
        'Spider',
        'Turtle',
        'Rabbit',
        'Bear',
        'Lion',
        'Tiger',
        'Elephant',
        'Monkey',
        'Cattle',
        'Sheep',
        'Goat',
        'Chicken',
        'Duck',
        'Penguin',
        'Owl',
        'Snake',
        'Frog',
        'Shark',
        'Whale',
        'Dolphin',
        'Squirrel',
        'Deer',
        'Fox',
        'Wolf',
        'Mouse',
        'Pig',
        'Camel',
        'Dinosaur',
        'Zoo',
        'Pet',
        'Wildlife',
        'Feather',
        'Fur',
        'Snout',
        'Whiskers',
        'Paw',
      ],
    ),
    VisualGroup(
      terms: [
        'food',
        'أكل',
        'طعام',
        'مأكولات',
        'وجبة',
        'essen',
        'lebensmittel',
        'comida',
        'nourriture',
        'cibo',
        'eten',
        'voedsel',
      ],
      labels: [
        'Food',
        'Dessert',
        'Cake',
        'Bread',
        'Fruit',
        'Vegetable',
        'Ice cream',
        'Pizza',
        'Hamburger',
        'Sandwich',
        'Pasta',
        'Rice',
        'Soup',
        'Salad',
        'Meat',
        'Seafood',
        'Cheese',
        'Chocolate',
        'Cookie',
        'Candy',
        'Breakfast',
        'Lunch',
        'Dinner',
        'Barbecue',
        'Sushi',
        'Noodle',
        'Egg',
        'Honey',
        'Cooking',
        'Baking',
        'Restaurant',
        'Cuisine',
        'Dish',
        'Recipe',
        'Tableware',
        'Plate',
      ],
    ),
    VisualGroup(
      terms: [
        'drink',
        'مشروب',
        'مشروبات',
        'شراب',
        'getränk',
        'getränke',
        'bebida',
        'bebidas',
        'boisson',
        'bevanda',
        'drankje',
        'dranken',
      ],
      labels: [
        'Drink',
        'Coffee',
        'Tea',
        'Juice',
        'Wine',
        'Beer',
        'Cocktail',
        'Water',
        'Milk',
        'Bottle',
        'Cup',
        'Mug',
        'Smoothie',
      ],
    ),
    VisualGroup(
      terms: [
        'person',
        'people',
        'شخص',
        'ناس',
        'أشخاص',
        'انسان',
        'وجه',
        'menschen',
        'leute',
        'gente',
        'personas',
        'gens',
        'personnes',
        'persone',
        'mensen',
        'pessoas',
      ],
      labels: [
        'Person',
        'Selfie',
        'Smile',
        'Face',
        'Hair',
        'Baby',
        'Child',
        'Crowd',
        'Wedding',
        'Bride',
        'Groom',
        'Portrait',
        'Beard',
        'Eyelash',
        'Nail',
        'Tattoo',
        'Hairstyle',
        'Chin',
        'Forehead',
        'Eyebrow',
        'Lip',
        'Neck',
        'Shoulder',
      ],
    ),
    VisualGroup(
      terms: [
        'nature',
        'طبيعة',
        'منظر طبيعي',
        'outdoors',
        'خارجي',
        'natur',
        'naturaleza',
        'natura',
        'natuur',
        'natureza',
      ],
      labels: [
        'Sky',
        'Cloud',
        'Sunset',
        'Sunrise',
        'Beach',
        'Mountain',
        'Snow',
        'Waterfall',
        'Lake',
        'River',
        'Sea',
        'Ocean',
        'Forest',
        'Desert',
        'Tree',
        'Plant',
        'Flower',
        'Leaf',
        'Grass',
        'Garden',
        'Rock',
        'Island',
        'Rain',
        'Rainbow',
        'Star',
        'Moon',
        'Night',
        'Landscape',
        'Sand',
        'Wave',
        'Horizon',
        'Sunlight',
        'Field',
        'Valley',
      ],
    ),
    VisualGroup(
      terms: [
        'vehicle',
        'مركبة',
        'مواصلات',
        'سيارات',
        'transport',
        'fahrzeug',
        'verkehr',
        'vehículo',
        'transporte',
        'véhicule',
        'veicolo',
        'trasporto',
        'voertuig',
        'vervoer',
        'veículo',
      ],
      labels: [
        'Car',
        'Vehicle',
        'Bicycle',
        'Motorcycle',
        'Boat',
        'Airplane',
        'Train',
        'Bus',
        'Truck',
        'Ship',
        'Helicopter',
        'Traffic',
        'Road',
        'Wheel',
        'Tire',
        'Automotive',
        'Windshield',
        'Bumper',
      ],
    ),
    VisualGroup(
      terms: [
        'building',
        'مبنى',
        'مباني',
        'عمارة',
        'architecture',
        'gebäude',
        'architektur',
        'edificio',
        'arquitectura',
        'bâtiment',
        'architettura',
        'gebouw',
        'architectuur',
        'arquitetura',
      ],
      labels: [
        'Building',
        'Skyscraper',
        'House',
        'Bridge',
        'Temple',
        'Castle',
        'Church',
        'Mosque',
        'Tower',
        'City',
        'Street',
        'Architecture',
        'Window',
        'Door',
        'Stairs',
        'Roof',
        'Wall',
        'Facade',
        'Skyline',
      ],
    ),
    VisualGroup(
      terms: [
        'home',
        'بيت',
        'منزل',
        'داخلي',
        'interior',
        'ديكور',
        'zuhause',
        'wohnung',
        'einrichtung',
        'casa',
        'hogar',
        'maison',
        'intérieur',
        'interni',
        'thuis',
        'woning',
        'interieur',
      ],
      labels: [
        'Room',
        'Kitchen',
        'Bathroom',
        'Bedroom',
        'Furniture',
        'Interior design',
        'Table',
        'Chair',
        'Bed',
        'Sofa',
        'Lamp',
        'Curtain',
        'Shelf',
        'Cabinet',
        'Floor',
        'Mirror',
      ],
    ),
    VisualGroup(
      terms: [
        'sport',
        'رياضة',
        'رياضي',
        'fitness',
        'تمرين',
        'deporte',
        'deportes',
        'sports',
        'esporte',
        'desporto',
      ],
      labels: [
        'Sports',
        'Football',
        'Soccer',
        'Basketball',
        'Baseball',
        'Tennis',
        'Swimming',
        'Surfing',
        'Skiing',
        'Cycling',
        'Running',
        'Gym',
        'Yoga',
        'Boxing',
        'Golf',
        'Volleyball',
        'Skateboard',
        'Fitness',
        'Stadium',
        'Ball',
        'Athlete',
      ],
    ),
    VisualGroup(
      terms: [
        'music',
        'موسيقى',
        'أغاني',
        'حفلة موسيقية',
        'musik',
        'música',
        'musique',
        'musica',
        'muziek',
      ],
      labels: [
        'Music',
        'Guitar',
        'Piano',
        'Drum',
        'Concert',
        'Singing',
        'Microphone',
        'Violin',
        'Dance',
        'Performance',
        'Stage',
        'Musician',
        'Speaker',
      ],
    ),
    VisualGroup(
      terms: [
        'tech',
        'تقنية',
        'الكترونيات',
        'أجهزة',
        'device',
        'technik',
        'gerät',
        'elektronik',
        'tecnología',
        'dispositivo',
        'technologie',
        'appareil',
        'tecnologia',
        'apparaat',
        'elektronica',
      ],
      labels: [
        'Laptop',
        'Computer',
        'Mobile phone',
        'Keyboard',
        'Camera',
        'Watch',
        'Television',
        'Headphones',
        'Robot',
        'Technology',
        'Gadget',
        'Screen',
        'Monitor',
        'Charger',
        'Cable',
      ],
    ),
    VisualGroup(
      terms: [
        'document',
        'مستند',
        'ورق',
        'وثيقة',
        'paper',
        'dokument',
        'papier',
        'documento',
        'papel',
        'carta',
        'documenten',
      ],
      labels: [
        'Book',
        'Newspaper',
        'Paper',
        'Document',
        'Text',
        'Handwriting',
        'Map',
        'Menu',
        'Poster',
        'Receipt',
        'Calendar',
        'Whiteboard',
        'Magazine',
        'Envelope',
        'Note',
      ],
    ),
    VisualGroup(
      terms: [
        'art',
        'فن',
        'رسم',
        'تصميم',
        'design',
        'kunst',
        'arte',
        'diseño',
        'dibujo',
        'dessin',
        'disegno',
        'ontwerp',
        'desenho',
      ],
      labels: [
        'Painting',
        'Drawing',
        'Sketch',
        'Comics',
        'Cartoon',
        'Anime',
        'Illustration',
        'Art',
        'Graffiti',
        'Sculpture',
        'Design',
        'Pattern',
        'Colorfulness',
        'Font',
        'Logo',
      ],
    ),
    VisualGroup(
      terms: [
        'shopping',
        'تسوق',
        'ملابس',
        'موضة',
        'fashion',
        'einkaufen',
        'mode',
        'kleidung',
        'compras',
        'moda',
        'ropa',
        'achats',
        'vêtements',
        'winkelen',
        'kleding',
        'roupa',
      ],
      labels: [
        'Shopping',
        'Clothing',
        'Dress',
        'Shoe',
        'Bag',
        'Handbag',
        'Jewellery',
        'Sunglasses',
        'Hat',
        'Suit',
        'Shirt',
        'Jeans',
        'Store',
        'Market',
        'Fashion',
        'Sleeve',
        'Textile',
        'Boutique',
      ],
    ),
    VisualGroup(
      terms: [
        'celebration',
        'مناسبة',
        'احتفال',
        'عيد',
        'حفلة',
        'feier',
        'fest',
        'celebración',
        'fiesta',
        'fête',
        'célébration',
        'festa',
        'feest',
        'celebração',
      ],
      labels: [
        'Party',
        'Birthday',
        'Wedding',
        'Gift',
        'Balloon',
        'Cake',
        'Fireworks',
        'Christmas',
        'Celebration',
        'Candle',
        'Decoration',
        'Event',
        'Ceremony',
      ],
    ),
    VisualGroup(
      terms: [
        'game',
        'لعبة',
        'ألعاب',
        'قيمنق',
        'gaming',
        'spiel',
        'spiele',
        'juego',
        'juegos',
        'jeu',
        'jeux',
        'gioco',
        'giochi',
        'spel',
        'spellen',
        'jogo',
        'jogos',
      ],
      labels: [
        'Game',
        'Video game',
        'Toy',
        'Doll',
        'Chess',
        'Card',
        'Puzzle',
        'Playing',
        'Controller',
        'Console',
      ],
    ),
  ];

  /// Every word that should find a screenshot carrying [labels], normalized.
  ///
  /// The label itself always comes first — see the class doc on why nothing
  /// here is allowed to be the *only* way to reach a picture.
  static Set<String> searchTermsFor(Iterable<String> labels) {
    final Set<String> terms = {};

    // Filtered here as well as at extraction time, so a library indexed
    // before [mediumLabels] existed stops answering "shows a phone" for every
    // screenshot in it without needing a re-scan.
    for (final String label in meaningful(labels)) {
      terms.add(normalize(label));

      for (final String synonym in synonyms[label] ?? const []) {
        terms.add(normalize(synonym));
      }
      for (final VisualGroup group in groups) {
        if (!group.labels.contains(label)) continue;
        for (final String term in group.terms) {
          terms.add(normalize(term));
        }
      }
    }

    terms.remove('');
    return terms;
  }

  /// Whether a screenshot carrying [labels] should surface for [query].
  ///
  /// Matching is by prefix in **both** directions: a term that starts with
  /// the query catches "قط" → "قطة" (still typing), and a query that starts
  /// with a term catches "cats" → "Cat" (a plural the tables don't list).
  /// Plain substring matching was rejected — it makes "at" return every cat
  /// in the library, and a search that answers questions nobody asked is
  /// worse than one that misses.
  static bool matches(Iterable<String> labels, String query) {
    final String needle = normalize(query);
    if (needle.length < minimumQueryLength) return false;

    return searchTermsFor(
      labels,
    ).any((term) => term.startsWith(needle) || needle.startsWith(term));
  }

  /// The labels on a screenshot that actually caused [query] to match, so the
  /// UI can show *why* a picture came back. A visual match is a guess, and a
  /// guess the user can see is one they can judge.
  static List<String> matchingLabels(Iterable<String> labels, String query) {
    final String needle = normalize(query);
    if (needle.length < minimumQueryLength) return const [];

    return [
      for (final String label in labels)
        if (matches([label], needle)) label,
    ];
  }

  /// Folds away the spelling differences that make a search miss.
  ///
  /// **Two folds, because the tables hold two kinds of writing.** Somebody
  /// typing "قطه" and a table entry reading "قطة" are the same word; so are
  /// "kase" and "Käse", "cafe" and "café", "leao" and "leão". Neither side of
  /// either pair is wrong, and this runs on the query and on every stored term
  /// alike, so no table here has to be spelled defensively.
  ///
  /// The Arabic half is the older one and has drawn blood before — the
  /// classifier once shipped a bug purely because ta marbuta was left out of
  /// it. The Latin half was missing entirely for as long as this file held no
  /// Latin words but English ones: six of the seven languages the app now
  /// ships in write accents, and an accent costs two key presses, so the
  /// unaccented spelling is the one people actually type.
  ///
  /// [foldForMatching] does the Latin half and the lower-casing, including
  /// text that arrives already decomposed. The two passes cannot collide —
  /// it drops combining marks in U+0300–U+036F, and Arabic harakat live at
  /// U+064B–U+0652.
  static String normalize(String input) {
    final StringBuffer buffer = StringBuffer();

    for (final int rune in foldForMatching(input).runes) {
      // Harakat (fatha..sukun) and tatweel carry no meaning when searching.
      if (rune >= 0x064B && rune <= 0x0652) continue;
      if (rune == 0x0640) continue;

      buffer.writeCharCode(switch (rune) {
        0x0623 || 0x0625 || 0x0622 || 0x0671 => 0x0627, // أ إ آ ٱ → ا
        0x0649 => 0x064A, // ى → ي
        0x0629 => 0x0647, // ة → ه
        _ => rune,
      });
    }

    return buffer.toString().trim().replaceAll(RegExp(r'\s+'), ' ');
  }
}

/// A broad category and the specific model labels that belong to it.
class VisualGroup {
  final List<String> terms;
  final List<String> labels;

  const VisualGroup({required this.terms, required this.labels});
}
